### ISSUE TITLE
Additional Props to Template

### ISSUE THREAD

**Issue by mira-thakkar** [StreakYC/react-draggable-list#1]
I have implemented react-draggable-list in my react component. It is working perfectly fine. Now my issue is i want to pass additional props to template component. How is it possible??

**Comment by AgentME** [comment]
You can make the item parameter be an object containing more values, or you can define the template component within a closure that can capture more values:

```js
class Foo extends React.Component {
  //...
  render() {
    let label = Math.random();
    return (
      <DraggableList
        itemKey="name"
        template={props => <div>{label}: {props.item}</div>}
        list={this.state.list}
        onMoveEnd={newList => this.setState({list: newList})}
        container={()=>document.body}
      />
    );
  }
}
```

**Comment by bernatfortet** [comment]
Hello,

When I use this approach I get:

> Warning: Stateless function components cannot be given refs (See ref "template" in message created by TemplateContainer). Attempts to access this ref will fail.

What can I do about it?

Thanks

**Comment by AgentME** [comment]
I'm sorry, when I wrote that I forgot that the template parameter doesn't accept stateless functions. You can do something like this instead where you map over the list to stick more values in the item prop:

```js
class Foo extends React.Component {
  //...
  render() {
    let label = Math.random();
    return (
      <DraggableList
        itemKey="name"
        template={Template}
        list={this.state.list.map(item => ({...item, label}))}
        onMoveEnd={newList => this.setState({list: newList})}
        container={()=>document.body}
      />
    );
  }
}
```

**Comment by bernatfortet** [comment]
Awesome this worked!
Btw, on the example that you just provided the map only worked for me if the list was an object as opposed than an array. (for future readers)
