### ISSUE TITLE
Height defaults back to 200px instead of 'auto' when template is arrow function

### ISSUE THREAD

**Issue by joepsz** [StreakYC/react-draggable-list#11]
Thanks for making, sharing and maintaining this library!

When I implemented this library, I used the ES6 arrow notation for the template component. When I did that, the component had a height of 200px whenever I tried to drag it. That seemed like a weird default to me. 

Since the documentation mentioned using the optional `getDragHeight` method on the template component, I suspected that the library may try to call a method on an arrow function. The bug disappeared when I rewrote the component as a `class Template extends React.Component`.

Perhaps the documentation should specify to not use the arrow syntax or the height should somehow not default to 200px for arrow syntax components.

**Comment by AgentME** [comment]
React doesn't allow refs to stateless functional components, which breaks the part of the code which tries to read the element's current height. I'll update the documentation to include this limitation.

(The library could be changed to try to find the height of the internal TemplateContainer component which is the owner of the user's provided template, but there might be other issues I haven't noticed too, and I think I'd like to recommend a normal class to encourage implementing `getDragHeight`, `shouldComponentUpdate`, etc, and to discourage the possibility that someone passes a new anonymous functional component on every render.)
