### ISSUE TITLE
How to set upper and lower bounds for dragged items?

### ISSUE THREAD

**Issue by clintharris** [StreakYC/react-draggable-list#12]
Great library--thanks for sharing.

Any advice on the best way to limit the y-coord for dragged items such that they stay within the container? I've overridden `_handleMouseMove` so that I can recognize when the dragged item's bounding box goes above/below the container, but I'm not sure about the best way to _correctly_ stop the item from moving. Here's what I've been experimenting with:
```
class MyDraggableList extends DraggableList {
  
  constructor(props) {
    super(props);
    this._oldHandleMouseMove = this._handleMouseMove;
    this._handleMouseMove = this._newHandleMouseMove;
  }

  _newHandleMouseMove({pageY, clientY}) {

    const { lastDrag } = this.state;
    const { top: containerTop, bottom: containerBottom } = super._getContainer().getBoundingClientRect();
    const { natural: listItemHeight } = this._heights.get(lastDrag.itemKey);
    const listItem = this.getItemInstance(lastDrag.itemKey);
    const { top: listItemTop, bottom: listItemBottom } = findDOMNode(listItem).getBoundingClientRect();

    console.debug(`containerTop:${containerTop}, listItemTop:${listItemTop}, containerBottom:${containerBottom}, clientY:${clientY}, pageY:${pageY}`);
    
    if(listItemTop < containerTop) {
      console.warn('Dragged ABOVE the container');
      this.setState({lastDrag: {...lastDrag, mouseY: containerTop, startY: containerTop}});
      return;
    }
    else if(listItemBottom > containerBottom) {
      console.warn('Dragged BELOW the container');
      return;
    }

    this._oldHandleMouseMove({pageY, clientY});
  }
}
```
The problem is that once the list item goes outside the bounds (i.e., I just `return`), I can't get things to work again by dragging back within the normal container bounds.

**Comment by clintharris** [comment]
For future reference, here's the solution that I'm using for now: https://gist.github.com/clintharris/b552f61120c593cccdd37063372dd77f

**Comment by AgentME** [comment]
There's now a `constrainDrag` prop on DraggableList in v3.6.0 that causes the items to be constrained within the list.
