### ISSUE TITLE
draggingIndex is always null

### ISSUE THREAD

**Issue by thierryskoda** [StreakYC/react-draggable-list#13]
Hi,

In my implementation I'm always getting `draggingIndex: null`  on : `updateState={(value) => console.log("value", value)}`  when I drag div arround.

Am I doing something wrong?  Even with the example I can't make it work ... :( 

Thanks to anyone!

**Comment by AgentME** [comment]
What is the updateState function? Can you show more of your code and what version of React you're using?

**Comment by thierryskoda** [comment]
Was related to another problem! It's okay sorry!
