### ISSUE TITLE
Every item in the list is unmounted and re-mounted at start and end of drag

### ISSUE THREAD

**Issue by pelotom** [StreakYC/react-draggable-list#14]
It looks like both at the start and end of a drag, each item in the list gets unmounted and then remounted. This leads to unattractive discontinuities in style animations, not to mention being inefficient. Why is it necessary it unmount any items at all, when nothing is ever being removed, only reordered?

**Comment by AgentME** [comment]
Do you see this behavior in the included example? Can you show your code?

If you pass a new class object as the `template` prop on every render, then you may see this behavior as React won't believe that the old and new items are of the same type.

**Comment by pelotom** [comment]
Ah, I am passing a new class object for the template prop every time, so that would explain what I'm seeing. However, I don't see any way around doing this, because I need to configure the template component based on the props and state of the parent, and

1. `DraggableList` does not appear to have a way to pass arbitrary properties through to the items
2. It seems that the template is not allowed to be a stateless functional component because `DraggableList` expects to be able to get a `ref` for it

What am I missing?

**Comment by pelotom** [comment]
Ah, I guess I need to declare the template class as an instance variable of the component.

**Comment by pelotom** [comment]
Ok, that worked 👍 Thanks.
