### ISSUE TITLE
unsetZIndex does not work.

### ISSUE THREAD

**Issue by lukaswelinder** [StreakYC/react-draggable-list#21]
Only setting the `z-index` to `auto` is not preventing the list items from creating a stacking context.

Relatively or absolutely positioned elements create their own [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), since the parent and item position is set to `relative` when not animating, they are still creating a stacking context.

**Comment by AgentME** [comment]
According to that page, relatively or absolutely positioned elements with z-index:auto do not create a stacking context, which matches my experience.

>positioned (absolutely or relatively) with a z-index value other than "auto",

If you have an example where it seems like the right thing isn't happening, I'd be happy to help with it.
