### ISSUE TITLE
Feature Request: Pass index of item into template

### ISSUE THREAD

**Issue by bslinger** [StreakYC/react-draggable-list#24]
I'm finding this library super useful so far, but have one request: I'd like to render the list items differently depending on where they are in the list (ie. first item will be a different colour) - would it be possible to have an additional prop passed to the template component with its position in the list?

**Comment by AgentME** [comment]
Many number-related styling concerns can be addressed directly through CSS, and the application can always pass the index to each item on the list on every render.

Passing the order prop to each template component would mean that each template component must be re-rendered when the order prop changes (unless the application's component defines a shouldComponentUpdate method; granted, we do already recommend this, but I'm hesitant to add more things that necessitate it if they are things that are already solvable with the current API).

Additionally, if the order prop updates while the list is being reordered (while the user still has the mouse down, before they've released and onMoveEnd is called), then it's possible that a user may make the mistake of having a callback on an item identify the item by its current order prop, which won't be equal to the item's current index in the list during a drag.

-----

Here's some examples of how to do various number-related things as diffs against the [example page](https://github.com/StreakYC/react-draggable-list/tree/master/example).

* Numbering the items:

```diff
diff --git a/example/main.css b/example/main.css
index 1685699..b12b264 100644
--- a/example/main.css
+++ b/example/main.css
@@ -5,19 +5,24 @@
 
 .list {
   width: 430px;
   margin: 10px auto;
   padding: 15px;
+  counter-reset: my-list-counter;
 }
 .item {
   border: 1px solid black;
   overflow: hidden;
   transform-origin: 30% 50% 0px;
   padding-left: 20px;
   background: white;
   max-height: 100%;
 }
+.item::before {
+  content: counter(my-list-counter);
+  counter-increment: my-list-counter;
+}
 .item .dragHandle {
   visibility: hidden;
   position: absolute;
   top: 0;
   left: 0;
```

* Applying a style to the top-most item:

```diff
diff --git a/example/main.css b/example/main.css
index 1685699..538f570 100644
--- a/example/main.css
+++ b/example/main.css
@@ -8,6 +8,9 @@
   margin: 10px auto;
   padding: 15px;
 }
+.list > * > :nth-child(2) .item {
+  background: rgb(128,128,128);
+}
 .item {
   border: 1px solid black;
   overflow: hidden;
```

* Passing the index into each of the items for use in JS:

```diff
diff --git a/example/Example.js b/example/Example.js
index 1516766..0e10aba 100644
--- a/example/Example.js
+++ b/example/Example.js
@@ -11,7 +11,7 @@ type PlanetListItem = {
 };
 
 type PlanetProps = {
-  item: PlanetListItem;
+  item: PlanetListItem & {index: number};
   itemSelected: number;
   dragHandle: *;
 };
@@ -49,7 +49,7 @@ class PlanetItem extends React.Component<PlanetProps, PlanetState> {
         }}
       >
         {dragHandle(<div className="dragHandle" />)}
-        <h2>{ item.name }</h2>
+        <h2>{ item.name } -  {item.index}</h2>
         {item.subtitle &&
           <div className="subtitle">This item has a subtitle visible while dragging</div>
         }
@@ -107,7 +107,7 @@ export default class Example extends React.Component<{}, ExampleState> {
     this.setState({useContainer: !this.state.useContainer});
   }
 
-  _onListChange(newList: Array<PlanetListItem>) {
+  _onListChange(newList: Array<*>) {
     this.setState({list: newList});
   }
 
@@ -148,7 +148,7 @@ export default class Example extends React.Component<{}, ExampleState> {
           <DraggableList
             itemKey="name"
             template={PlanetItem}
-            list={this.state.list}
+            list={this.state.list.map((item, index) => ({...item, index}))}
             onMoveEnd={newList => this._onListChange(newList)}
             container={()=>useContainer ? this._container : document.body}
           />
```

If you're not sure how to apply these strategies in some cases, or there are other use-cases that the above strategies can't work for, then please bring it up! And sorry for not responding to this sooner!
