### ISSUE TITLE
Expose whether list is currently being interacted with

### ISSUE THREAD

**Issue by JayHales** [StreakYC/react-draggable-list#51]
Is there currently a way to expose whether or not the list is currently being interacted with? My specific case is that I need a repeated API call to stop updating the list when I am interacting.

If there's not do you want me to implement it?

Many thanks.

**Comment by Macil** [comment]
There isn't currently a way to check this. I'd accept a PR implementing `onDragStart(): void` and `onDragEnd(): void` props.

**Comment by JayHales** [comment]
Cool, I'll take a look.
