### ISSUE TITLE
List reverts to original position after re-render

### ISSUE THREAD

**Issue by bernatfortet** [StreakYC/react-draggable-list#7]
It's hard to explain by writing so I made a video: https://youtu.be/69Y72HXZE4s (sorry for the poor quality I can't upload a huge file :(

here's my class using `DraggableList`
```js
class MessagesContainer extends Component {
  constructor(props){
    super(props)
    this.state = {
      list: []
    }
  }

  componentWillReceiveProps(nextProps) {
    console.log( 'NextProps list:', nextProps.step.messages[0].text  )
    //this.setState({ list: this._transformMessageToDraggableList(nextProps.step.messages) })
  }

  render(){
    console.log( 'MESSAGES CONTAINER —— Rendering', this.props.step.messages[0].text )
    return(
      <div>{this.props.step.messages[0].text }
        <DraggableList
          itemKey='key'
          template={Message}
          list={ this._transformMessageToDraggableList(this.props.step.messages)  }
          onMoveEnd={newList => this._onListChange(newList)}
          container={()=> document.body }
        />
      </div>
    )
  }

  _transformMessageToDraggableList = (messages) => {
    console.log( 'Transforming => ', messages[0].text  )
    let stepId = this.props.step.id
    let newArray = []

    messages.forEach( (value, index) => {
      let newMessage = {
        key: index,
        stepId: stepId,
        messageId: index,
        message: messages[index],
      }
      newArray[index] = newMessage
    })

    console.log( 'Into => ', newArray[0].message.text  )

    return newArray
  }

  _onListChange(newList) {
    let messages = []
    newList.forEach( (item, index) => {
      messages[index] = item.message
    })
    console.log( 'newList', newList  )
    console.log( '--------------')
    this.setState({ list: newList})
    this.props.storeMessages( this.props.step.id, messages )
  }

}
```

**Comment by AgentME** [comment]
The issue is that you're making the keys of the items be dependent on their current position in the list.

```js
    messages.forEach( (value, index) => {
      let newMessage = {
        key: index,
        stepId: stepId,
        messageId: index,
        message: messages[index],
      }
      newArray[index] = newMessage
    })
```

You're setting the key property to the message's current index. The key property is how react-draggable-list identifies the items. When the user drags the item 0 to the second position in the list, you're doing a setState and immediately re-rendering with item 0 back in the first position of the list (with new data) which confuses DraggableList.

**Comment by bernatfortet** [comment]
@AgentME the objects that come through my list are of different types. Not all of them share the same attributes. What would you recommend in that case?

Thanks a lot for your quick response!

**Comment by bernatfortet** [comment]
Also, not all my list items have the same height:
Here's a video showing it

**Comment by AgentME** [comment]
react-draggable-list currently requires that all of its items have a key that persists even while the items are re-ordered. If the items represent things from a server that each have unique ids, then use those. Otherwise you should create a random or otherwise unique id for each item.

You can make it so items have different heights by implementing a `getDragHeight()` method on your template component.

**Comment by bernatfortet** [comment]
Ok, So that worked great! For the record:
I'm generating a random Id for my list item when creating the list:
```js
<DraggableList
  itemKey={this._getListItemKey}
  template={Message}
  list={ this._transformMessageToDraggableList(this.props.step.messages)  }
  onMoveEnd={newList => this._onListChange(newList)}
  container={()=> document.body }
/>

_transformMessageToDraggableList = (messages) => {
  let stepId = this.props.step.id
  let newArray = []

  messages.forEach( (value, index) => {
    let newMessage = {
      key: index,
      id: Math.round( Math.random() *10000 ),
      stepId: stepId,
      messageId: index,
      message: messages[index],
    }
    newArray[index] = newMessage
  })

  return newArray
}

_getListItemKey = (item) => {
  return item.id
}
```

**Comment by bernatfortet** [comment]
But now I'm getting this error:
Basically the separation between list items goes crazy and then re-establishes itself.
Here's a video: https://youtu.be/gB820tZ_OAM

**Comment by AgentME** [comment]
You should generate the random keys once, not on every re-render.
