### ISSUE TITLE
nested Drag and Drop?

### ISSUE THREAD

**Issue by craig1123** [StreakYC/react-draggable-list#9]
Is it possible for this library to have a nested drag and drop. The screenshot below has sections that are draggable and sortable and items within sections that are draggable, sortable, and dropable to other sections. Right now, I'm using react-DND, but I like the smoothness of this library more. Do you guys support this?

![screen shot 2016-12-06 at 9 59 24 am](https://cloud.githubusercontent.com/assets/17581359/20935123/bca448cc-bb9a-11e6-9246-58a38173281b.png)

**Comment by AgentME** [comment]
Nesting react-draggable-list instances inside of each other works fine.

**Comment by AgentME** [comment]
Sorry, I missed the part about the inner sections being draggable to other sections. That part is not supported and we don't have plans for that at this time.

**Comment by barbarosso** [comment]
@craig1123  Did you find a solution for the nested drag and drop?
If so can you tell me some more about it?

**Comment by craig1123** [comment]
Not with this library. I went back to using React DnD with it working. I did want to use this library since it seems more intuitive and cleaner ui

**Comment by barbarosso** [comment]
@craig1123 How did you solve it with react-dnd? Any tips you can share?

**Comment by craig1123** [comment]
I referenced this example: http://gaearon.github.io/react-dnd/examples-sortable-simple.html. When dragging the outer layer, it is pretty much the same as the example. The inner layer is trickier. When splicing the index of the card, you have to check both the index of the outer layer and inner layer. 
For example: 
```
// change cards in same section
if (indice === sectionIndex && dragIndex !== hoverIndex){
  //splice dragIndex of the inner layer card and replace it with the hoverIndex
}

// change cards in different sections
else if (indice !== sectionIndex){
  // splice index of outer layer
}
```

**Comment by sk-yamgar** [comment]
@AgentME is there a document available to implement nested react-draggable-list? In case of above examples I need sections draggable and the inner sections draggable inside that section only.
